version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ethara_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ethara_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/inventory_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ethara_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
